version: '3.1'

services:

  ghost:
    container_name: standard-ghost
    image: ghost:1.14-alpine
    restart: always
    ports:
      - 2368:2368
    volumes:
      - ./public/ghost:/var/lib/ghost/content
      - ./config/ghost/config.development.json:/var/lib/ghost/config.development.json
